# Generated by Django 4.2.3 on 2023-09-09 15:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("name", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "photos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Review",
                "verbose_name_plural": "Ad Reviews",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_date", models.DateField(verbose_name="Event Date")),
                (
                    "is_archived_vendor",
                    models.BooleanField(
                        default=False, verbose_name="Is Archived Vendor"
                    ),
                ),
                (
                    "is_archived_client",
                    models.BooleanField(
                        default=False, verbose_name="Is Archived Client"
                    ),
                ),
                (
                    "is_read_vendor",
                    models.BooleanField(default=False, verbose_name="Is Read Vendor"),
                ),
                (
                    "is_read_client",
                    models.BooleanField(default=False, verbose_name="Is Read Client"),
                ),
                (
                    "is_delete_vendor",
                    models.BooleanField(default=False, verbose_name="Is Delete Vendor"),
                ),
                (
                    "is_delete_client",
                    models.BooleanField(default=False, verbose_name="Is Delete Client"),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("full_name", models.TextField(verbose_name="Full Name")),
                ("phone", models.TextField(verbose_name="Phone")),
                ("event_date", models.DateField(verbose_name="Event Date")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact Request",
                "verbose_name_plural": "Contact Requests",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FavouriteAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Favourite Ad",
                "verbose_name_plural": "Favourite Ads",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "attachments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="analytics.chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-id"],
            },
        ),
    ]
