# Generated by Django 4.2.3 on 2023-08-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adreview",
            options={
                "ordering": ["-id"],
                "verbose_name": "Ad Review",
                "verbose_name_plural": "Ad Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="chat",
            options={
                "ordering": ["-id"],
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
            },
        ),
        migrations.AlterModelOptions(
            name="contactrequest",
            options={
                "ordering": ["-id"],
                "verbose_name": "Contact Request",
                "verbose_name_plural": "Contact Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="favouritead",
            options={
                "ordering": ["-id"],
                "verbose_name": "Favourite Ad",
                "verbose_name_plural": "Favourite Ads",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-id"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterField(
            model_name="chat",
            name="is_delete_client",
            field=models.BooleanField(default=False, verbose_name="Is Delete Client"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="is_delete_vendor",
            field=models.BooleanField(default=False, verbose_name="Is Delete Vendor"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="is_read_client",
            field=models.BooleanField(default=False, verbose_name="Is Read Client"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="latest_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_message",
                to="analytics.message",
                verbose_name="Last Message",
            ),
        ),
    ]
