# Generated by Django 4.2.3 on 2023-09-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favouritead",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_saved",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.AddField(
            model_name="favouritead",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_fav_ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_contacts",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_chats",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_chats",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="latest_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_message",
                to="analytics.message",
                verbose_name="Last Message",
            ),
        ),
        migrations.AddField(
            model_name="adreview",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_reviews",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.AddField(
            model_name="adreview",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_reviews",
                to="clients.client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favouritead",
            unique_together={("ad", "user")},
        ),
    ]
