# Generated by Django 4.2.3 on 2023-08-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_adreview_chat_message_delete_adviewed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-id"]},
        ),
    ]
