# Generated by Django 4.2.3 on 2023-09-09 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_adreview_options_alter_chat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
    ]
