# Generated by Django 4.2.3 on 2023-09-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
    ]
