# Generated by Django 4.2.3 on 2023-10-05 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_stripe_customer_id"),
        ("ads", "0006_remove_country_slug"),
        ("analytics", "0003_alter_message_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dates",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Dates"
                    ),
                ),
                ("hide", models.BooleanField(default=True, verbose_name="Hide")),
                (
                    "ad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_canlender",
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_calender",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calender",
                "verbose_name_plural": "Calenders",
                "ordering": ["-id"],
            },
        ),
    ]
