# Generated by Django 4.2.3 on 2023-11-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("analytics", "0004_calender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adreview",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_reviews",
                to="clients.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="adreview",
            name="message",
            field=models.TextField(default="D"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adreview",
            name="rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
