# Generated by Django 4.2.3 on 2024-03-11 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0011_alter_ad_offered_services"),
        ("analytics", "0005_alter_adreview_client_alter_adreview_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visitor_ip", models.GenericIPAddressField()),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad View",
                "verbose_name_plural": "Ad Views",
                "ordering": ["-id"],
                "unique_together": {("ad", "visitor_ip", "user")},
            },
        ),
    ]
