# Generated by Django 4.2.3 on 2023-07-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('vendor_user', 'vendor_user')], default='vendor_user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('vendor', 'vendor')], default='vendor', max_length=50),
        ),
    ]
