# Generated by Django 4.2.3 on 2023-07-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_url_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
