# Generated by Django 4.2.3 on 2023-10-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.TextField(blank=True, null=True),
        ),
    ]
