# Generated by Django 4.2.3 on 2023-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.TextField(blank=True, null=True),
        ),
    ]
