# Generated by Django 4.2.3 on 2023-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_avatar_url_remove_user_linked_entity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
