# Generated by Django 4.2.3 on 2023-11-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified'),
        ('users', '0006_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
    ]
