# Generated by Django 4.2.3 on 2023-08-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_delete_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-id"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
