# Generated by Django 4.2.3 on 2023-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
