# Generated by Django 4.2.3 on 2023-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "super_admin"),
                    ("vendor", "vendor"),
                    ("client", "client"),
                ],
                default="vendor",
                max_length=50,
            ),
        ),
    ]
