# Generated by Django 4.2.3 on 2023-09-09 15:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivationSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activation Sub Category",
                "verbose_name_plural": "Activation Sub Categories",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(default="Ad", verbose_name="Commercial Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "website",
                    models.TextField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "city",
                    models.TextField(blank=True, null=True, verbose_name="Oras/Comuna"),
                ),
                (
                    "street",
                    models.TextField(blank=True, null=True, verbose_name="Strada"),
                ),
                (
                    "number",
                    models.TextField(blank=True, null=True, verbose_name="Numar"),
                ),
                (
                    "full_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresa completa"
                    ),
                ),
                (
                    "facebook",
                    models.TextField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram",
                    models.TextField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "youtube",
                    models.TextField(blank=True, null=True, verbose_name="Youtube"),
                ),
                (
                    "tiktok",
                    models.TextField(blank=True, null=True, verbose_name="Tiktok"),
                ),
                (
                    "twitter",
                    models.TextField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "others",
                    models.TextField(blank=True, null=True, verbose_name="Others"),
                ),
                (
                    "offered_services",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "site_services",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="Total Views"),
                ),
            ],
            options={
                "verbose_name": "Ad",
                "verbose_name_plural": "Ad's",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Categorie")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Judet")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="SectionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="SiteFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_faq_category",
                        to="ads.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_faq_section",
                        to="ads.sectionname",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site FAQ",
                "verbose_name_plural": "Site FAQ's",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Sub Categorie")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="ads.category",
                        verbose_name="Categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "suggestion",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "site_faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_faq_questions",
                        to="ads.sitefaq",
                        verbose_name="Site FAQ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Question",
                "verbose_name_plural": "Site Questions",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="sitefaq",
            name="sub_category",
            field=models.ManyToManyField(
                related_name="site_faq_sub_category",
                to="ads.subcategory",
                verbose_name="Sub Category",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "sub_category",
                    models.ManyToManyField(
                        related_name="question_sub_category",
                        to="ads.subcategory",
                        verbose_name="Sub Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RelatedSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_category_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_category_relation_1",
                        to="ads.subcategory",
                        verbose_name="SubCategorie 1",
                    ),
                ),
                (
                    "sub_category_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_category_relation_2",
                        to="ads.subcategory",
                        verbose_name="SubCategorie 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Related Sub Category",
                "verbose_name_plural": "Related Sub Categories",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_urls",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Media"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_media",
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_faqs",
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ'S",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AdFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_faq_ad",
                        to="ads.ad",
                        verbose_name="Commercial",
                    ),
                ),
                (
                    "site_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_faq_site_question",
                        to="ads.sitequestion",
                        verbose_name="Site Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad FAQ",
                "verbose_name_plural": "Ad FAQ's",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="activation_countries",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="country_ads",
                to="ads.country",
                verbose_name="Judete in care oferiti serviciile mentionate",
            ),
        ),
    ]
