# Generated by Django 4.2.3 on 2023-09-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.country",
                verbose_name="Judet",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="related_sub_categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_sub_category_ads",
                to="ads.subcategory",
                verbose_name="Related Sub Categorie",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_ads",
                to="ads.subcategory",
                verbose_name="Sub Categorie",
            ),
        ),
        migrations.AddField(
            model_name="activationsubcategory",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_countries",
                to="ads.subcategory",
                verbose_name="SubCategorie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relatedsubcategory",
            unique_together={("sub_category_1", "sub_category_2")},
        ),
    ]
