# Generated by Django 4.2.3 on 2023-07-25 04:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_municipality_alter_company_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='Oras/Comuna'),
        ),
        migrations.AddField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.country', verbose_name='Judet'),
        ),
        migrations.AddField(
            model_name='ad',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='ad',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresa completa'),
        ),
        migrations.AddField(
            model_name='ad',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='ad',
            name='number',
            field=models.TextField(blank=True, null=True, verbose_name='Numar'),
        ),
        migrations.AddField(
            model_name='ad',
            name='offered_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ad',
            name='others',
            field=models.URLField(blank=True, null=True, verbose_name='Others'),
        ),
        migrations.AddField(
            model_name='ad',
            name='street',
            field=models.TextField(blank=True, null=True, verbose_name='Strada'),
        ),
        migrations.AddField(
            model_name='ad',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='Tiktok'),
        ),
        migrations.AddField(
            model_name='ad',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='ad',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='ad',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='activation_countries',
            field=models.ManyToManyField(related_name='country_ads', to='ads.country', verbose_name='Judete in care oferiti serviciile mentionate'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='related_sub_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sub_category_ads', to='ads.subcategory', verbose_name='Related Sub Categorie'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_ads', to='ads.subcategory', verbose_name='Sub Categorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(verbose_name='Judet'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_media', to='ads.ad', verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media',
            field=models.TextField(blank=True, null=True, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ads.category', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(verbose_name='Sub Categorie'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(verbose_name='Question')),
                ('type', models.CharField(choices=[('text_field', 'text_field'), ('checkbox', 'checkbox')], max_length=50, verbose_name='Type')),
                ('answer_input', models.TextField(blank=True, null=True, verbose_name='Answer Input')),
                ('answer_checkbox', models.BooleanField(default=False, verbose_name='Answer Checkbox')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.subcategory', verbose_name='Sub Categorie')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdsFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_faqs', to='ads.ad', verbose_name='Ad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_ads', to='ads.faq', verbose_name='Faq')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
