# Generated by Django 4.2.3 on 2023-09-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="sub_category",
            field=models.ManyToManyField(
                related_name="service_sub_category",
                to="ads.subcategory",
                verbose_name="Sub Category",
            ),
        ),
    ]
