# Generated by Django 4.2.3 on 2023-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_service_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="activation_countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="country_ads",
                to="ads.country",
                verbose_name="Judete in care oferiti serviciile mentionate",
            ),
        ),
    ]
