# Generated by Django 4.2.3 on 2023-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_options_remove_adsfaqs_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='media',
        ),
        migrations.AddField(
            model_name='gallery',
            name='media_urls',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Media'),
        ),
    ]
