# Generated by Django 4.2.3 on 2023-08-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0004_remove_gallery_media_gallery_media_urls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={},
        ),
        migrations.RemoveField(
            model_name="faq",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="faq",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_faqs",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.DeleteModel(
            name="AdsFaqs",
        ),
    ]
