# Generated by Django 4.2.3 on 2023-10-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_country_image_url_country_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="slug",
        ),
    ]
