# Generated by Django 4.2.3 on 2023-11-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_ad_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Sort Order"),
        ),
    ]
