# Generated by Django 4.2.3 on 2023-08-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_ad_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activationsubcategory",
            options={
                "verbose_name": "Activation Sub Category",
                "verbose_name_plural": "Activation Sub Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "Ad", "verbose_name_plural": "Ad's"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQ'S"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Galleries"},
        ),
        migrations.AlterModelOptions(
            name="relatedsubcategory",
            options={
                "verbose_name": "Related Sub Category",
                "verbose_name_plural": "Related Sub Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="facebook",
            field=models.TextField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="instagram",
            field=models.TextField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="others",
            field=models.TextField(blank=True, null=True, verbose_name="Others"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="tiktok",
            field=models.TextField(blank=True, null=True, verbose_name="Tiktok"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="twitter",
            field=models.TextField(blank=True, null=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="website",
            field=models.TextField(blank=True, null=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="youtube",
            field=models.TextField(blank=True, null=True, verbose_name="Youtube"),
        ),
        migrations.AlterField(
            model_name="relatedsubcategory",
            name="sub_category_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_relation_1",
                to="ads.subcategory",
                verbose_name="SubCategorie 1",
            ),
        ),
        migrations.AlterField(
            model_name="relatedsubcategory",
            name="sub_category_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_relation_2",
                to="ads.subcategory",
                verbose_name="SubCategorie 2",
            ),
        ),
    ]
