# Generated by Django 4.2.3 on 2023-11-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_ad_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="ad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_media",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
    ]
