# Generated by Django 4.2.3 on 2023-11-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_sort_order'),
        ('ads', '0008_alter_gallery_ad'),
    ]

    operations = [
    ]
