# Generated by Django 4.2.3 on 2023-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0008_alter_activationsubcategory_options_alter_ad_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="total_views",
            field=models.IntegerField(default=0, verbose_name="Total Views"),
        ),
    ]
