# Generated by Django 4.2.3 on 2023-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_merge_0008_ad_sort_order_0008_alter_gallery_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="number",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contact Person"
            ),
        ),
    ]
