# Generated by Django 4.2.3 on 2023-08-29 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_ad_slug_ad_total_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activationsubcategory",
            options={
                "ordering": ["-id"],
                "verbose_name": "Activation Sub Category",
                "verbose_name_plural": "Activation Sub Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-id"],
                "verbose_name": "Ad",
                "verbose_name_plural": "Ad's",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["-id"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ'S",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ["-id"],
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
            },
        ),
        migrations.AlterModelOptions(
            name="relatedsubcategory",
            options={
                "ordering": ["-id"],
                "verbose_name": "Related Sub Category",
                "verbose_name_plural": "Related Sub Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["-id"],
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(unique=True, verbose_name="Categorie"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.TextField(unique=True, verbose_name="Judet"),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "sub_category",
                    models.ManyToManyField(
                        related_name="question_sub_category",
                        to="ads.subcategory",
                        verbose_name="Sub Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["-id"],
            },
        ),
    ]
