# Generated by Django 4.2.3 on 2023-08-29 20:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0010_alter_activationsubcategory_options_alter_ad_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_faq_category",
                        to="ads.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin FAQ",
                "verbose_name_plural": "Admin FAQ's",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SectionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="AdminQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "suggestion",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "admin_faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_faq",
                        to="ads.adminfaq",
                        verbose_name="Admin FAQ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Question",
                "verbose_name_plural": "Admin Questions",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="adminfaq",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_faq_section",
                to="ads.sectionname",
                verbose_name="Section",
            ),
        ),
        migrations.AddField(
            model_name="adminfaq",
            name="sub_category",
            field=models.ManyToManyField(
                related_name="admin_faq_sub_category",
                to="ads.subcategory",
                verbose_name="Sub Category",
            ),
        ),
    ]
