# Generated by Django 4.2.3 on 2023-08-30 10:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0010_alter_activationsubcategory_options_alter_ad_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="SiteFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_faq_category",
                        to="ads.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_faq_section",
                        to="ads.sectionname",
                        verbose_name="Section",
                    ),
                ),
                (
                    "sub_category",
                    models.ManyToManyField(
                        related_name="site_faq_sub_category",
                        to="ads.subcategory",
                        verbose_name="Sub Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site FAQ",
                "verbose_name_plural": "Site FAQ's",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "suggestion",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "site_faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_faq",
                        to="ads.sitefaq",
                        verbose_name="Site FAQ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Question",
                "verbose_name_plural": "Site Questions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AdFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_faq_ad",
                        to="ads.ad",
                        verbose_name="Commercial",
                    ),
                ),
                (
                    "site_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_faq_site_question",
                        to="ads.sitequestion",
                        verbose_name="Site Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad FAQ",
                "verbose_name_plural": "Ad FAQ's",
                "ordering": ["-id"],
            },
        ),
    ]
