# Generated by Django 4.2.3 on 2023-08-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0011_sectionname_sitefaq_sitequestion_adfaq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitequestion",
            name="site_faq",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_faq_questions",
                to="ads.sitefaq",
                verbose_name="Site FAQ",
            ),
        ),
    ]
