# Generated by Django 4.2.3 on 2023-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0012_alter_sitequestion_site_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="activation_countries",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="country_ads",
                to="ads.country",
                verbose_name="Judete in care oferiti serviciile mentionate",
            ),
        ),
    ]
