# Generated by Django 4.2.3 on 2023-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0013_alter_ad_activation_countries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_checkbox",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_input",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="sub_category",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="type",
        ),
        migrations.AddField(
            model_name="faq",
            name="answer",
            field=models.TextField(default="S", verbose_name="Answer"),
            preserve_default=False,
        ),
    ]
