# Generated by Django 4.2.3 on 2023-09-06 04:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0014_remove_faq_answer_checkbox_remove_faq_answer_input_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="site_services",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
    ]
