# Generated by Django 4.2.3 on 2023-09-19 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_company_stripe_customer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free", "free"),
                            ("standard", "standard"),
                            ("advanced", "advanced"),
                            ("featured", "featured"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("allowed_ads", models.IntegerField(verbose_name="Allowed Ads")),
                (
                    "allowed_ad_photos",
                    models.IntegerField(verbose_name="Allowed Ad Photos"),
                ),
                (
                    "allowed_ad_videos",
                    models.IntegerField(verbose_name="Allowed Ad Videos"),
                ),
                ("reviews", models.BooleanField(verbose_name="Reviews")),
                ("faq", models.BooleanField(verbose_name="FAQ")),
                (
                    "offered_services",
                    models.BooleanField(verbose_name="Offered Services"),
                ),
                ("pdf_upload", models.BooleanField(verbose_name="Pdf Upload")),
                ("analytics", models.BooleanField(verbose_name="Analytics")),
                ("calender", models.BooleanField(verbose_name="Calender")),
            ],
            options={
                "verbose_name": "Subscription Type",
                "verbose_name_plural": "Subscription Types",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription_id",
                    models.TextField(
                        blank=True, null=True, verbose_name="Subscription Id"
                    ),
                ),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
                (
                    "canceled_at",
                    models.TextField(blank=True, null=True, verbose_name="Canceled At"),
                ),
                (
                    "price_id",
                    models.TextField(blank=True, null=True, verbose_name="Plan Id"),
                ),
                (
                    "unit_amount",
                    models.TextField(blank=True, null=True, verbose_name="Unit Amount"),
                ),
                (
                    "latest_invoice_id",
                    models.TextField(
                        blank=True, null=True, verbose_name="Latest Invoice Id"
                    ),
                ),
                (
                    "client_secret",
                    models.TextField(
                        blank=True, null=True, verbose_name="Client Secret"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("cancelled", "cancelled"),
                            ("paused", "paused"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_subscriptions",
                        to="companies.company",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
