# Generated by Django 4.2.3 on 2023-09-01 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0008_company_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free", "free"),
                            ("standard", "standard"),
                            ("advanced", "advanced"),
                            ("featured", "featured"),
                        ],
                        default="free",
                        max_length=150,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_subscriptions",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
