# Generated by Django 4.2.3 on 2023-09-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="canceled_at",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="client_secret",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="latest_invoice_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="price_id",
        ),
    ]
