# Generated by Django 4.2.3 on 2023-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="extras",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
