# Generated by Django 4.2.3 on 2023-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_extras"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="extras",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="type",
        ),
        migrations.AddField(
            model_name="subscription",
            name="canceled_at",
            field=models.TextField(blank=True, null=True, verbose_name="Canceled At"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="client_secret",
            field=models.TextField(default=1, verbose_name="Client Secret"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="latest_invoice_id",
            field=models.TextField(default=1, verbose_name="Latest Invoice Id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="price_id",
            field=models.TextField(default=1, verbose_name="Plan Id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.TextField(default=1, verbose_name="Status"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_id",
            field=models.TextField(default=1, verbose_name="Subscription Id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="unit_amount",
            field=models.TextField(default=1, verbose_name="Unit Amount"),
            preserve_default=False,
        ),
    ]
