# Generated by Django 4.2.3 on 2023-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_remove_subscription_canceled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="price_id",
            field=models.TextField(blank=True, null=True, verbose_name="Price Id"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.TextField(
                blank=True, null=True, verbose_name="Stripe Customer Id"
            ),
        ),
    ]
