# Generated by Django 4.2.3 on 2023-09-28 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_stripe_customer_id"),
        ("subscriptions", "0003_subscription_price_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method_id",
                    models.TextField(verbose_name="Payment Method Id"),
                ),
                ("brand", models.TextField(verbose_name="Brand")),
                ("last_4", models.TextField(verbose_name="Last 4")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method_company",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "PaymentMethod",
                "verbose_name_plural": "PaymentMethods",
            },
        ),
    ]
