# Generated by Django 4.2.3 on 2023-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="exp_month",
            field=models.TextField(blank=True, null=True, verbose_name="Expiry Month"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="exp_year",
            field=models.TextField(blank=True, null=True, verbose_name="Expiry Year"),
        ),
    ]
