# Generated by Django 4.2.3 on 2023-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_paymentmethod_exp_month_paymentmethod_exp_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("cancelled", "cancelled"),
                    ("unpaid", "unpaid"),
                ],
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
