# Generated by Django 4.2.3 on 2023-09-09 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(verbose_name="Denumire Firma")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "postal_code",
                    models.TextField(blank=True, null=True, verbose_name="Cod Postal"),
                ),
                (
                    "fiscal_code",
                    models.TextField(blank=True, null=True, verbose_name="Cod Fiscal"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="adresa"),
                ),
                (
                    "firm_number",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nr. Reg. Comertului"
                    ),
                ),
                (
                    "bank_name",
                    models.TextField(blank=True, null=True, verbose_name="Banca"),
                ),
                (
                    "bank_iban",
                    models.TextField(blank=True, null=True, verbose_name="IBAN"),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_companies",
                        to="ads.country",
                        verbose_name="Judet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
