# Generated by Django 4.2.3 on 2023-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="stripe_customer_id",
            field=models.TextField(
                blank=True, null=True, verbose_name="Stripe Customer Id"
            ),
        ),
    ]
