# Generated by Django 4.2.3 on 2023-10-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(default="S", verbose_name="adresa"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.TextField(default="S"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="fiscal_code",
            field=models.TextField(default="1", verbose_name="Cod Fiscal"),
            preserve_default=False,
        ),
    ]
