# Generated by Django 4.2.3 on 2023-10-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
