# Generated by Django 4.2.3 on 2023-11-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_company_address_alter_company_city_and_more"),
        ("companies", "0004_company_is_verified"),
    ]

    operations = []
