# Generated by Django 4.2.3 on 2023-07-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_phone_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
    ]
