# Generated by Django 4.2.3 on 2023-08-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_remove_company_created_by_remove_company_updated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
    ]
