# Generated by Django 4.2.3 on 2023-11-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_merge_20231101_1644"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="is_verified",
        ),
    ]
