# Generated by Django 4.2.3 on 2023-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
