# Generated by Django 4.2.3 on 2023-08-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_company_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.TextField(blank=True, null=True),
        ),
    ]
