# Generated by Django 4.2.3 on 2023-08-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
    ]
